# Generated by Django 3.0.5 on 2020-11-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
