# Generated by Django 3.0.5 on 2020-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201120_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
